update build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -97,14 +97,12 @@ function purge_all() {
     rm -rf release
 }
 
-function build_all() {
+function build_debug() {
     ROOT=`pwd`
     DEBUG=debug
-    RELEASE=release
 
     cd $ROOT
     if [ ! -d $DEBUG ]; then mkdir $DEBUG; fi
-    if [ ! -d $RELEASE ]; then mkdir $RELEASE; fi
 
     OS="Unknown-OS"
     case "$OSTYPE" in
@@ -117,18 +115,45 @@ function build_all() {
     echo [fastype] prepare for $OS
 
     cd $DEBUG && cmake -DF_OS=$OS -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON .. && make VERBOSE=1 && cd $ROOT
+    cd $ROOT
+}
+
+function build_release() {
+    ROOT=`pwd`
+    RELEASE=release
+
+    cd $ROOT
+    if [ ! -d $RELEASE ]; then mkdir $RELEASE; fi
+
+    OS="Unknown-OS"
+    case "$OSTYPE" in
+      solaris*) OS="Solaris" ;;
+      darwin*)  OS="MacOSX" ;;
+      linux*)   OS="Linux" ;;
+      bsd*)     OS="BSD" ;;
+      *)        echo "[fastype] error! unknown *$OSTYPE* !" && exit 3 ;;
+    esac
+    echo [fastype] prepare for $OS
+
     cd $RELEASE && cmake -DF_OS=$OS -DCMAKE_BUILD_TYPE=Release .. && make -j8 && cd $ROOT
+    cd $ROOT
+}
+
+function build_help() {
+    echo [fastype] help message:
+    echo [fastype]     1. build init    - initialize third party dependencies.
+    echo [fastype]     2. build debug   - build debug version.
+    echo [fastype]     3. build release - build release version.
+    echo [fastype]     4. build all     - build both debug and release version.
+    echo [fastype]     5. build install - build and install.
+    echo [fastype]     6. build test    - run unit tests.
+    echo [fastype]     7. build clean   - clean build objects.
 }
 
 # ---- main ----
 
 if [ "$1" = "help" ]; then
-    echo [fastype] help message:
-    echo [fastype]     1. build init    - initialize third party libraries and other dependencies.
-    echo [fastype]     2. build         - build all.
-    echo [fastype]     3. build install - build and install.
-    echo [fastype]     4. build test    - run unit tests.
-    echo [fastype]     5. build clean   - clean build objects.
+    build_help
     exit 0
 fi
 
@@ -162,4 +187,20 @@ if [ "$1" = "test" ]; then
     exit 0
 fi
 
-build_all
+if [ "$1" = "debug" ]; then
+    build_debug
+    exit 0
+fi
+
+if [ "$1" = "release" ]; then
+    build_release
+    exit 0
+fi
+
+if [ "$1" = "all" ]; then
+    build_debug
+    build_release
+    exit 0
+fi
+
+build_help
